# TODO:: 삭제 (임시)
jwt:
  secret: "8OieD8qFft9YPJ83x2B7bQqihu5NSqanEZZA6+ZH74UrvyIgVCgbbJJo/i9bzruz/gT7VqAU+xCa+UIhFuWlyQ=="


spring:
  #snake_case로 api 컬럼값 출력되도록 설정
  jackson:
    property-naming-strategy: SNAKE_CASE

  application:
    name: heatguard-ai-back
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/HGAIBACK
    username: {USERNAME}
    password: {PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  #jwt:
  # secret: ${JWT_SECRET_KEY} # 추후 배포 서버에 저장하고 사용