spring:
  jackson:
    property-naming-strategy: SNAKE_CASE        # snake_case로 api 컬럼값 출력되도록 설정
    time-zone: Asia/Seoul                       # 서버가 작동되는 시간대를 KST로 설정
  application:
    name: heatguard-ai-back
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_NAME}                             # 데이터베이스 URL
    username: ${DB_ID}                          # 데이터베이스 ID
    password: ${DB_PW}                          # 데이터베이스 비밀번호

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  #게시판 업로드 파일 max 크기 정의
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  config:
    import: optional:classpath:personal.yaml, optional:classpath:aws-secret.yaml

app:
  base-url: "https://heatguard.duckdns.org:30216/" # 서버 URL(HTTPS)
  notice-file:
    upload-dir: ./uploads/notice    # S3와 연결되면 무시됨(삭제 안해도 오류 안 남)
    max-size-bytes: 10485760        # 10MB
    allowed-ext: pdf,png,jpg,jpeg   # 지정 확장자
  s3:
    bucket: "hgaiback-s3"           # 실제 S3 버킷 이름
    region: "ap-northeast-2"
    base-prefix: "notice"           # S3 key 최상위 폴더명
    presign-expire-minutes: 10      # S3 URL 유효시간 10분
 
